### ISSUE TITLE
Error con el ejercicio: Universo cerrado

### ISSUE THREAD

**Issue by mumukivictor** [pdep-utn/mumuki-guia-logico-teoria-hechos-y-reglas#1]
Buenas tardes! Les escribo porque cuando estaba ejecutando la prueba me aparecía un mensaje  de warning además del yes o no.

Les adjunto la imagen de lo que mostraba. Saludos!
Natalí
![issue-universo cerrado-01](https://cloud.githubusercontent.com/assets/19732612/15782980/b75babda-2982-11e6-8313-5f37a4597326.jpg)

**Comment by flbulgarelli** [comment]
Resuelto!
